app = "discord-bot-vgbrha"

[build]
dockerfile = "Dockerfile"

[deploy]
strategy = "rolling"

[env]
PORT = "8080"

[experimental]
auto_rollback = true

  [experimental.attached]
  secrets = { }

[[services]]
internal_port = 8080
protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [services.http]
    auto_stop_machines = "suspend"
    auto_start_machines = true
    min_machines_running = 0
